---
title: "Dyad Models"
---

```{r, setup, include=FALSE, cache=TRUE}
project.root = rprojroot::find_rstudio_root_file()
knitr::opts_knit$set(root.dir = project.root) # for future chunks
setwd(project.root) # for this chunk
print(getwd())
source('./scripts/analysis/010-run-model-batches.R')
```


```{r, dyad.plots, echo=FALSE, results='asis'}
source('./reports/utils.R')

for (experiment.name in names(DYAD_EXPERIMENTS)) {
  cat('\n\n##',experiment.name,'\n')
  
  experiment = DYAD_EXPERIMENTS[[experiment.name]]

  plot.interval.consonance(experiment$behaviour$summary$interval,
                           experiment$behaviour$summary$rating,
                           experiment$behaviour$full$data$interval,
                           experiment$behaviour$full$data$rating,
                           title=paste(experiment.name,'behaviour'))
  
  models = list(
    'periodicity.duplex'   = experiment$models$`mami.codi.m.1.t.1.h.2.l.-1.r.73.5759`,
    'interference.simplex' = experiment$models$`Hutchinson & Knopoff (1978)`,
    "harmonicity.simplex"  = experiment$models$`Harrison & Pearce (2018)`,
    'periodicity.simplex'  = experiment$models$`mami.codi.m.1.t.1.h.0.l.0.r.73.5759`
  )
  
  for (model.name in names(models)) {
    model = models[[model.name]]
    plot.interval.consonance(model$full$profile$interval,
                             model$full$profile$output,
                             model$full$raw_profile$interval,
                             model$full$raw_profile$output,
                             title=paste(experiment.name,model.name))
  }
}
```