RESOLUTION_BEHAVIOURAL_1D <- 1000
RESOLUTION_BEHAVIOURAL_2D <- 500

BANDWIDTH_GSP_2D <- 0.375

DEFAULT_RESOLUTION_MODEL_1D <- 1000 
DEFAULT_RESOLUTION_MODEL_2D <- 100 # Used to be 500 without smoothing, but with smoothing there's not much point

ROLL_OFF_SMOOTH <- 1.5
BEHAVIOURAL_SMOOTH_BROAD <- 0.2
BEHAVIOURAL_SMOOTH_NARROW <- 0.035

COHERENT_WAVES <- TRUE

BOOTSTRAP_REPS <- 1000
